apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
  labels:
    app: tushartest
    environment: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: frontend
  template:
    metadata:
      labels:
        environment: frontend
    spec:
      containers:
      - name: nginx1
        image: nginx:1.14.2
      nodeSelector:
        hardware: lowspec
