apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: In
            values:
            - lowspec            
  containers:
  - name: nginx
    image: nginx

#Operators:
#In
#NotIn
#Exists
#DoesNotExist
