apiVersion: v1
kind: Service
metadata:
 name: tushartest
 labels:
    app: tushartest
    environment: frontend
spec:
  type: NodePort
  selector:
    environment: frontend
  ports:
    - protocol: TCP
      port: 80