apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsshare
spec:
  capacity:
    storage: 5Gi            # Size of the nfs-server volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  nfs:
    path: /nfs_share         # path on which k8-n-4 exposes the nfs mount
    server: 10.128.0.2   # nfs-server ip address