apiVersion: v1
kind: Pod
metadata:
  name: nvolpod3
spec:
  containers:
    - name: test
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html" # Folder in pod mounting nfsclient 
        name: mypd
  volumes:
    - name: mypd             # volume name the container can mount
      persistentVolumeClaim: # Source of storage
        claimName: nfsclient  # name of pvc created