apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: readiness
  name: readiness
spec:
  replicas: 3
  selector:
    matchLabels:
      app: readiness
  template:
    metadata:
      labels:
        app: readiness
    spec:
      containers:
      - image: nginx
        name: readiness
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command:
            - cat
            - /var/ready
          failureThreshold: 3 # unhelathy thresold
          initialDelaySeconds: 15
          periodSeconds: 10 # Interval 
          successThreshold: 1  # healthy
          timeoutSeconds: 1 # timeout




#---------


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: readiness
  name: readiness
spec:
  replicas: 3
  selector:
    matchLabels:
      app: readiness
  template:
    metadata:
      labels:
        app: readiness
    spec:
      containers:
      - image: devopstechlab1/kubweb
        name: readiness
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
